shufler_shufler:
    resource: "@SHUFLERShuflerBundle/Resources/config/routing.yml"
    prefix:   /

shufler_language:
    path:  /
    defaults: {_controller: "SHUFLERShuflerBundle:Video:index", permanent: true}

shufler_user_update:
    path: /update
    defaults: {_controller: SHUFLERUserBundle:User:update}

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

security_forbidden:
    path: /forbidden
    defaults: {_controller: SHUFLERUserBundle:User:forbidden} 

rest : 
  type : rest 
  resource : "routing_rest.yml"
  prefix : /api

api_login_check:
   path: /api/login_check