<?php
namespace SHUFLER\ShuflerBundle\Entity;

/**
 * AlbumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbumRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get Albums
     *
     * @return mixed|\Doctrine\DBAL\Driver\Statement|array|NULL
     */
    public function getAlbums($api=null) {
        $query = $this->_em->createQueryBuilder()
        ->select('a')
        ->orderBy('a.name', 'ASC')
        ->from('SHUFLERShuflerBundle:Album', 'a');
       if($api){
        $query->where('a.youtubeKey is not null');
       }
        $albums = $query->getQuery()
        ->getResult();
        
        return $albums;
    }
}
