<?php
namespace SHUFLER\ShuflerBundle\Entity;

/**
 * ArtisteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtisteRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get Artistes
     *
     * @return mixed|\Doctrine\DBAL\Driver\Statement|array|NULL
     */
    public function getArtistes() {
        $query = $this->_em->createQueryBuilder()
        ->select('a')
        ->orderBy('a.name', 'ASC')
        ->from('SHUFLERShuflerBundle:Artiste', 'a');

        $query->where('a.imageUrl IS NOT NULL');        

        $artistes = $query->getQuery()
        ->getResult();
        
        return $artistes;
    }
}
