<?php
namespace SHUFLER\ShuflerBundle\Entity;

/**
 * ChannelFluxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChannelFluxRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get Channels by type
     *
     * @param unknown $id
     * @return mixed|\Doctrine\DBAL\Driver\Statement|array|NULL
     */
    function getChannelFluxAudio()
    {
        return $this->_em->createQueryBuilder()
        ->select('c')
        ->where('c.provider_name is NULL')
        ->from('SHUFLERShuflerBundle:ChannelFlux', 'c');
    }
    
    function getChannelFluxVideo() {
        return $this->_em->createQueryBuilder()
        ->select('c')
        ->where('c.provider_name IS NOT NULL')
        ->from('SHUFLERShuflerBundle:ChannelFlux', 'c')
        ->getQuery()
        ->getResult();
    }
}
