<?php
namespace SHUFLER\ShuflerBundle\Entity;

/**
 * ChannelFluxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChannelFluxRepository extends \Doctrine\ORM\EntityRepository
{

}
