<?php

namespace SHUFLER\ShuflerBundle\Entity;

/**
 * FluxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FluxRepository extends \Doctrine\ORM\EntityRepository
{
	
	function getRSS(){
		$rss=$this->_em->createQueryBuilder()
		->select('a')
		->from('SHUFLERShuflerBundle:Flux','a')
		->orderBy('a.id', 'ASC')
		->getQuery()
		->getResult()
		;
	
		return $rss;
	}
	
	function getFlux($id){
		$flux=$this->_em->createQueryBuilder()
		->select('a')
		->where('a.id= :id')
		->setParameter('id',$id)
		->from('SHUFLERShuflerBundle:flux','a')
		->getQuery()
		->getSingleResult()
		;
	
		return $flux;
	}
	
}
