<?php
namespace SHUFLER\ShuflerBundle\Entity;

/**
 * LinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkRepository extends \Doctrine\ORM\EntityRepository
{

    function getLinks()
    {
        $links = $this->_em->createQueryBuilder()
            ->select('a')
            ->from('SHUFLERShuflerBundle:Link', 'a')
            ->orderBy('a.category', 'ASC')
            ->orderBy('a.name', 'ASC')
            ->getQuery()
            ->getResult();
        
        return $links;
    }

    function getCategories()
    {
        $categories = $this->_em->createQueryBuilder()
            ->select('distinct a.category')
            ->from('SHUFLERShuflerBundle:Link', 'a')
            ->orderBy('a.category', 'ASC')
            ->getQuery()
            ->getResult();
        
        return $categories;
    }
}
