<?php
namespace SHUFLER\ShuflerBundle\Entity;

/**
 * MoodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoodRepository extends \Doctrine\ORM\EntityRepository
{
}
